@baseUrl=http://localhost:1337
@idJohn=605330b8ca1216722d4c1dcb
@idJane=605334a8ca1216722d4c1dce
@jwtJohn=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTMzMGI4Y2ExMjE2NzIyZDRjMWRjYiIsImlhdCI6MTYxNjA2NTQ1NiwiZXhwIjoxNjE4NjU3NDU2fQ.3u04J7X_6XSoX-ENcFgSPVnhF_KFB8V72onOilFAC7I
@jwtJane=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTMzNGE4Y2ExMjE2NzIyZDRjMWRjZSIsImlhdCI6MTYxNjA2NTcwNCwiZXhwIjoxNjE4NjU3NzA0fQ.wm7pS22lkMR89t-IdbavfYs5w_wPCzZrdkfn6t7iMxM

# Cards

### All cards
GET {{baseUrl}}/cards

### Single card
GET {{baseUrl}}/cards/605330ccca1216722d4c1dcc

### Count cards
GET {{baseUrl}}/cards/count

### Create card
POST {{baseUrl}}/cards
Content-Type: application/json
Authorization: Bearer {{jwtJane}}

{
  "text": "Hello, this is Jane",
  "author": "{{idJane}}"
}


# Users

### All users
GET {{baseUrl}}/users

### Login user
POST {{baseUrl}}/auth/local
Content-Type: application/json

{
  "identifier": "jane@doe.com",
  "password": "17Hackers"
}

### Create user
POST {{baseUrl}}/auth/local/register
Content-Type: application/json

{
  "username": "Jane Doe",
  "email": "jane@doe.com",
  "password": "17Hackers"
}
