@baseUrl=http://localhost:1337
@idJohn=605330b8ca1216722d4c1dcb
@idJane=605334a8ca1216722d4c1dce
@jwtJohn=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTMzMGI4Y2ExMjE2NzIyZDRjMWRjYiIsImlhdCI6MTYxNjA2NTQ1NiwiZXhwIjoxNjE4NjU3NDU2fQ.3u04J7X_6XSoX-ENcFgSPVnhF_KFB8V72onOilFAC7I
@jwtJane=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTMzNGE4Y2ExMjE2NzIyZDRjMWRjZSIsImlhdCI6MTYxNjE0ODAzNSwiZXhwIjoxNjE4NzQwMDM1fQ.9UWf2rcWcw0rA--pS4uhvgxfyoRwhZ65zRkJnUB6q9E

# Cards

### All cards
GET {{baseUrl}}/cards

### Single card
GET {{baseUrl}}/cards/605330ccca1216722d4c1dcc

### Count cards
GET {{baseUrl}}/cards/count

### Create card
POST {{baseUrl}}/cards
Content-Type: application/json
Authorization: Bearer {{jwtJane}}

{
  "text": "Demo Part 2 started",
  "author": "{{idJane}}"
}

### Vote card
PATCH {{baseUrl}}/cards/605330ccca1216722d4c1dcc/vote
Content-Type: application/json
Authorization: Bearer {{jwtJane}}


# Users

### All users
GET {{baseUrl}}/users

### Login user
POST {{baseUrl}}/auth/local
Content-Type: application/json

{
  "identifier": "jane@doe.com",
  "password": "17Hackers"
}

### Create user
POST {{baseUrl}}/auth/local/register
Content-Type: application/json

{
  "username": "Summer",
  "email": "summer@doe.com",
  "password": "17Hackers"
}
